# Generated by Django 3.1.2 on 2024-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=20)),
                ('colour_image', models.ImageField(upload_to='Admin/Colour Image')),
            ],
        ),
    ]
