# Generated by Django 3.1.2 on 2022-04-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('pro_description', models.TextField(null=True)),
                ('pro_code', models.IntegerField(null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('pro_price', models.IntegerField(blank=True, null=True)),
                ('strike_price', models.IntegerField(blank=True, null=True)),
                ('pro_colour', models.CharField(max_length=50)),
                ('return_product', models.CharField(max_length=6, null=True)),
                ('return_period_days', models.IntegerField(null=True)),
                ('pro_height', models.IntegerField(null=True)),
                ('pro_width', models.IntegerField(null=True)),
                ('pro_length', models.IntegerField(null=True)),
                ('pro_image', models.ImageField(blank=True, default='Admin/Product Image/Main/2.jpg', null=True, upload_to='Admin/Product Image/Main')),
                ('pro_back_image', models.ImageField(blank=True, null=True, upload_to='Admin/Product Image/Back')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='Admin/Product Image/Feature')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategory.brandmodel')),
                ('catname_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel')),
            ],
        ),
    ]
