# Generated by Django 3.1.2 on 2024-03-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('pro_description', models.TextField(null=True)),
                ('pro_code', models.IntegerField(null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('pro_price', models.IntegerField(blank=True, null=True)),
                ('strike_price', models.IntegerField(blank=True, null=True)),
                ('pro_colour', models.CharField(max_length=50)),
                ('return_product', models.CharField(max_length=6, null=True)),
                ('return_period_days', models.IntegerField(null=True)),
                ('pro_height', models.IntegerField(null=True)),
                ('pro_width', models.IntegerField(null=True)),
                ('pro_length', models.IntegerField(null=True)),
                ('pro_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Admin/ProductImage/Main')),
                ('pro_back_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Admin/ProductImage/Back')),
                ('feature_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Admin/ProductImage/Feature')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategory.brandmodel')),
                ('catname_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rel', to='category.categorymodel')),
            ],
        ),
    ]
