# Generated by Django 3.1.2 on 2022-04-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='Admin/ProductImage/Feature'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pro_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='Admin/ProductImage/Back'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='Admin/ProductImage/Main'),
        ),
    ]
